=== Rumirr/lenguajeDeMarcas/Lenguaje_de_Marcas/public_html/DTD/ProvaXML.dtd
<?xml version="1.0" encoding="UTF-8"?>



<!ELEMENT arrel (fill, fill2, fill2, branca)>
<!ELEMENT fill (#PCDATA)>
<!ELEMENT fill2 (#PCDATA)>
<!ELEMENT branca (fill, fill, fill)>

=== Rumirr/lenguajeDeMarcas/Lenguaje_de_Marcas/public_html/DTD/ProvaXML.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<!DOCTYPE arrel SYSTEM 'ProvaXML.dtd'>

<arrel>
    <fill>txte</fill>
    <fill2>texte</fill2>
    <fill2>texte</fill2>
    <branca>
        <fill></fill>
        <fill></fill>
        <fill></fill>
    </branca>
</arrel>
